# Generated by Django 5.2.17 on 2026-09-25 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        # order_number's counter. nextval() is exempt from rollback, so an abandoned
        # checkout burns a number and the series has gaps by design.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS order_number_seq START 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS order_number_seq;",
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=200)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery')], max_length=16)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='order_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_not_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'shipped', 'delivered', 'cancelled'])), name='order_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_size', models.CharField(max_length=50)),
                ('variant_shade', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive')],
            },
        ),
    ]
