# Generated by Django 5.2.17 on 2026-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('inside_valley_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outside_valley_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'shipping settings',
                'db_table': 'shipping_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='shipping_settings_singleton'), models.CheckConstraint(condition=models.Q(('inside_valley_fee__gte', 0), ('outside_valley_fee__gte', 0)), name='shipping_settings_fees_not_negative'), models.CheckConstraint(condition=models.Q(('free_shipping_threshold__isnull', True), ('free_shipping_threshold__gt', 0), _connector='OR'), name='shipping_settings_threshold_positive')],
            },
        ),
    ]
