# Generated by Django 5.2.17 on 2026-09-27 04:58

from decimal import Decimal

from django.db import migrations

# Frozen here rather than imported: the values render.yaml carried when the fees
# stopped being environment variables (ADR 0017). Later changes are the merchant's.
SHIPPING_SETTINGS_ID = 1


def create_shipping_settings(apps, schema_editor):
    ShippingSettings = apps.get_model("orders", "ShippingSettings")
    ShippingSettings.objects.get_or_create(
        id=SHIPPING_SETTINGS_ID,
        defaults={
            "inside_valley_fee": Decimal("150.00"),
            "outside_valley_fee": Decimal("250.00"),
            "free_shipping_threshold": None,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shipping_settings'),
    ]

    operations = [
        migrations.RunPython(create_shipping_settings, migrations.RunPython.noop),
    ]
