# Generated by Django 5.2.17 on 2026-09-20 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cod', 'Cash on delivery'), ('khalti', 'Khalti')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pidx', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('raw_status', models.CharField(blank=True, default='', max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payment_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('method', 'khalti'), _negated=True), ('pidx__isnull', False), _connector='OR'), name='payment_khalti_requires_pidx')],
            },
        ),
    ]
